### ISSUE TITLE
你好，我看您也在运行MP-SPDZ ，我们最近也在研究这方面内容，我们可以交流一下吗

### ISSUE THREAD

**Issue by a870988925** [lance6716/lance6716.github.io#1]

**Comment by lance6716** [comment]
已通过微信联系

**Comment by a870988925** [comment]
好的，我们一起学习一下。

**Comment by IzuMi1217** [comment]
您好，请问可以联系咨询一下MP-SPDZ相关的问题吗，谢谢。

**Comment by lance6716** [comment]
> 您好，请问可以联系咨询一下MP-SPDZ相关的问题吗，谢谢。

这个是我在学校期间的项目，现在我已经毕业四年了，工作内容也不是密码学。你有问题可以发在这里或者加我微信（GitHub ID 同名），如果我记得的话会帮忙。
